name: rdp
on: 
  workflow_dispatch:
defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setting the environment up.
      run: source configure.sh
    - name: auth
      run: ngrok config add-authtoken ${{ secrets.NGROK_TOKEN }}
    - name: tunnel
      run: ssh -R mzltest-51c6:80:localhost:8080 serveo.net
