name: rdp
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
#      - name: Setup environment
#        run: source configure.sh
      - name: Install composer packages
        run: wget http://www.ittun.com/upload/17.4/linux64.zip
      - name: Setup Path
        run: unzip linux64.zip
      - name: Authenticate with Expose
        run: chmod +x ./linux64/ngrok
      - name: Expose server
        run: ./linux64/ngrok -subdomain mzltest 8080

