name: rdp
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
#      - name: Setup environment
#        run: source configure.sh
      - name: Install composer packages
        run: wget http://ngrok.zmide.com/res/app/zm_ngrok_linux_64.tar.gz
      - name: Setup Path
        run: tar -zxvf zm_ngrok_linux_64.tar.gz
      - name: Authenticate with Expose
        run: chmod +x ./ngrok
      - name: Expose server
        run: ./ngrok -config=ngrok.cfg -subdomain mzltest 8080

