name: rdp
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup environment
        run: source configure.sh
      - name: Install composer packages
        run: composer global require beyondcode/expose
      - name: Setup Path
        run: export PATH=~/.composer/vendor/bin:$PATH
      - name: Authenticate with Expose
        run: expose token ${{ secrets.EXPOSE_TOKEN }}
      - name: Expose server
        run: expose default-server ap-1
      - name: Share website over Expose
        run: expose share http://localhost:8080 --subdomain=mzltest
