name: rdp
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup environment
        run: source configure.sh
      - name: Install composer packages
        run: curl https://github.com/beyondcode/expose/raw/master/builds/expose -L --output expose
      - name: Setup Path
        run: chmod +x expose
      - name: Authenticate with Expose
        run: ./expose token ${{ secrets.EXPOSE_TOKEN }}
      - name: Expose server
        run: ./expose default-server ap-1
      - name: Share website over Expose
        run: ./expose share-port 8080
